(defun copy-stdin ()
  (let ((num 0))
    (do ((line (read-line nil) (read-line nil)))
	((not line) nil)
	(incf num)
	(format t "~a: ~a~%" num line))))

(defun copy-file (name)
  (with-open-file (in name)
		  (let ((num 0))
		    (do ((line (read-line in nil) (read-line in nil)))
			((not line) nil)
			(incf num)
			(format t "~a: ~a~%" num line)))))
